<a href="https://colab.research.google.com/github/TerteryanTatev/Data-Science-Data-Analysis/blob/main/exploratory_data_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("ariyoomotade/netflix-data-cleaning-analysis-and-visualization")

print("Path to dataset files:", path)

Path to dataset files: /kaggle/input/netflix-data-cleaning-analysis-and-visualization

In [ ]:
!file /kaggle/input/netflix-data-cleaning-analysis-and-visualization

/kaggle/input/netflix-data-cleaning-analysis-and-visualization: setgid, directory

In [ ]:
!ls /kaggle/input/netflix-data-cleaning-analysis-and-visualization

netflix1.csv

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("/kaggle/input/netflix-data-cleaning-analysis-and-visualization/netflix1.csv")
df

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,9/25/2021,2020,PG-13,90 min,Documentaries
1,s3,TV Show,Ganglands,Julien Leclercq,France,9/24/2021,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
2,s6,TV Show,Midnight Mass,Mike Flanagan,United States,9/24/2021,2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries"
3,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,9/22/2021,2021,TV-PG,91 min,"Children & Family Movies, Comedies"
4,s8,Movie,Sankofa,Haile Gerima,United States,9/24/2021,1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies"
...,...,...,...,...,...,...,...,...,...,...
8785,s8797,TV Show,Yunus Emre,Not Given,Turkey,1/17/2017,2016,TV-PG,2 Seasons,"International TV Shows, TV Dramas"
8786,s8798,TV Show,Zak Storm,Not Given,United States,9/13/2018,2016,TV-Y7,3 Seasons,Kids' TV
8787,s8801,TV Show,Zindagi Gulzar Hai,Not Given,Pakistan,12/15/2016,2012,TV-PG,1 Season,"International TV Shows, Romantic TV Shows, TV ..."
8788,s8784,TV Show,Yoko,Not Given,Pakistan,6/23/2018,2016,TV-Y,1 Season,Kids' TV
8789,s8786,TV Show,YOM,Not Given,Pakistan,6/7/2018,2016,TV-Y7,1 Season,Kids' TV

In [ ]:
df.drop_duplicates(inplace=True)
print(df)

     show_id     type                             title         director  \
0         s1    Movie              Dick Johnson Is Dead  Kirsten Johnson
1         s3  TV Show                         Ganglands  Julien Leclercq
2         s6  TV Show                     Midnight Mass    Mike Flanagan
3        s14    Movie  Confessions of an Invisible Girl    Bruno Garotti
4         s8    Movie                           Sankofa     Haile Gerima
...      ...      ...                               ...              ...
8785   s8797  TV Show                        Yunus Emre        Not Given
8786   s8798  TV Show                         Zak Storm        Not Given
8787   s8801  TV Show                Zindagi Gulzar Hai        Not Given
8788   s8784  TV Show                              Yoko        Not Given
8789   s8786  TV Show                               YOM        Not Given

            country  date_added  release_year rating   duration  \
0     United States   9/25/2021          2020  PG-13     90 min
1            France   9/24/2021          2021  TV-MA   1 Season
2     United States   9/24/2021          2021  TV-MA   1 Season
3            Brazil   9/22/2021          2021  TV-PG     91 min
4     United States   9/24/2021          1993  TV-MA    125 min
...             ...         ...           ...    ...        ...
8785         Turkey   1/17/2017          2016  TV-PG  2 Seasons
8786  United States   9/13/2018          2016  TV-Y7  3 Seasons
8787       Pakistan  12/15/2016          2012  TV-PG   1 Season
8788       Pakistan   6/23/2018          2016   TV-Y   1 Season
8789       Pakistan    6/7/2018          2016  TV-Y7   1 Season

                                              listed_in
0                                         Documentaries
1     Crime TV Shows, International TV Shows, TV Act...
2                    TV Dramas, TV Horror, TV Mysteries
3                    Children & Family Movies, Comedies
4      Dramas, Independent Movies, International Movies
...                                                 ...
8785                  International TV Shows, TV Dramas
8786                                           Kids' TV
8787  International TV Shows, Romantic TV Shows, TV ...
8788                                           Kids' TV
8789                                           Kids' TV

[8790 rows x 10 columns]

In [ ]:
df.isnull().sum()

show_id         0
type            0
title           0
director        0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
dtype: int64

In [ ]:
df['date_added'] = pd.to_datetime(df['date_added'])

df

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,2021-09-25,2020,PG-13,90 min,Documentaries
1,s3,TV Show,Ganglands,Julien Leclercq,France,2021-09-24,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
2,s6,TV Show,Midnight Mass,Mike Flanagan,United States,2021-09-24,2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries"
3,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,2021-09-22,2021,TV-PG,91 min,"Children & Family Movies, Comedies"
4,s8,Movie,Sankofa,Haile Gerima,United States,2021-09-24,1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies"
...,...,...,...,...,...,...,...,...,...,...
8785,s8797,TV Show,Yunus Emre,Not Given,Turkey,2017-01-17,2016,TV-PG,2 Seasons,"International TV Shows, TV Dramas"
8786,s8798,TV Show,Zak Storm,Not Given,United States,2018-09-13,2016,TV-Y7,3 Seasons,Kids' TV
8787,s8801,TV Show,Zindagi Gulzar Hai,Not Given,Pakistan,2016-12-15,2012,TV-PG,1 Season,"International TV Shows, Romantic TV Shows, TV ..."
8788,s8784,TV Show,Yoko,Not Given,Pakistan,2018-06-23,2016,TV-Y,1 Season,Kids' TV
8789,s8786,TV Show,YOM,Not Given,Pakistan,2018-06-07,2016,TV-Y7,1 Season,Kids' TV

In [ ]:
df['month_added'] =df['date_added'].dt.month_name()
df['year_added'] = pd.DatetimeIndex(df['date_added']).year
df['day_added'] = df['date_added'].dt.day_name()
df

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in,month_added,year_added,day_added
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,2021-09-25,2020,PG-13,90 min,Documentaries,September,2021,Saturday
1,s3,TV Show,Ganglands,Julien Leclercq,France,2021-09-24,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",September,2021,Friday
2,s6,TV Show,Midnight Mass,Mike Flanagan,United States,2021-09-24,2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries",September,2021,Friday
3,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,2021-09-22,2021,TV-PG,91 min,"Children & Family Movies, Comedies",September,2021,Wednesday
4,s8,Movie,Sankofa,Haile Gerima,United States,2021-09-24,1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies",September,2021,Friday
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8785,s8797,TV Show,Yunus Emre,Not Given,Turkey,2017-01-17,2016,TV-PG,2 Seasons,"International TV Shows, TV Dramas",January,2017,Tuesday
8786,s8798,TV Show,Zak Storm,Not Given,United States,2018-09-13,2016,TV-Y7,3 Seasons,Kids' TV,September,2018,Thursday
8787,s8801,TV Show,Zindagi Gulzar Hai,Not Given,Pakistan,2016-12-15,2012,TV-PG,1 Season,"International TV Shows, Romantic TV Shows, TV ...",December,2016,Thursday
8788,s8784,TV Show,Yoko,Not Given,Pakistan,2018-06-23,2016,TV-Y,1 Season,Kids' TV,June,2018,Saturday
8789,s8786,TV Show,YOM,Not Given,Pakistan,2018-06-07,2016,TV-Y7,1 Season,Kids' TV,June,2018,Thursday

In [ ]:
df.groupby("type").count()['show_id']

type
Movie      6126
TV Show    2664
Name: show_id, dtype: int64

In [ ]:
df.groupby(["director","type"]).size()

director             type
A. L. Vijay          Movie    2
A. Raajdheep         Movie    1
A. Salaam            Movie    1
A.R. Murugadoss      Movie    2
Aadish Keluskar      Movie    1
                             ..
Çagan Irmak          Movie    1
Ísold Uggadóttir     Movie    1
Óskar Thór Axelsson  Movie    1
Ömer Faruk Sorak     Movie    2
Şenol Sönmez         Movie    2
Length: 4581, dtype: int64

In [ ]:
df.groupby("director").count().nlargest(10, 'show_id')['show_id']

director
Not Given                 2588
Rajiv Chilaka               20
Alastair Fothergill         18
Raúl Campos, Jan Suter      18
Marcus Raboy                16
Suhas Kadav                 16
Jay Karas                   14
Cathy Garcia-Molina         13
Jay Chapman                 12
Martin Scorsese             12
Name: show_id, dtype: int64

In [ ]:
df.groupby(["country","type"]).size()

country       type
Argentina     Movie      56
              TV Show    20
Australia     Movie      61
              TV Show    53
Austria       Movie       8
                         ..
Uruguay       TV Show     1
Venezuela     Movie       2
Vietnam       Movie       7
West Germany  Movie       1
Zimbabwe      Movie       1
Length: 138, dtype: int64

In [ ]:
df.groupby("country").count().nlargest(20, 'show_id')['show_id']

country
United States     3240
India             1057
United Kingdom     638
Pakistan           421
Not Given          287
Canada             271
Japan              259
South Korea        214
France             213
Spain              182
Mexico             138
Egypt              123
Australia          114
Turkey             112
Nigeria            105
Germany            104
China              100
Brazil              88
Indonesia           86
Taiwan              86
Name: show_id, dtype: int64

In [ ]:
df.groupby(["listed_in","type"]).size()

listed_in                                                     type
Action & Adventure                                            Movie      128
Action & Adventure, Anime Features                            Movie        1
Action & Adventure, Anime Features, Children & Family Movies  Movie        4
Action & Adventure, Anime Features, Classic Movies            Movie        2
Action & Adventure, Anime Features, Horror Movies             Movie        1
                                                                        ...
TV Horror, TV Mysteries, Teen TV Shows                        TV Show      1
TV Horror, Teen TV Shows                                      TV Show      2
TV Sci-Fi & Fantasy, TV Thrillers                             TV Show      1
TV Shows                                                      TV Show     16
Thrillers                                                     Movie       65
Length: 513, dtype: int64

In [ ]:
df.groupby("listed_in").count().nlargest(20, 'show_id')['show_id']

listed_in
Dramas, International Movies                         362
Documentaries                                        359
Stand-Up Comedy                                      334
Comedies, Dramas, International Movies               274
Dramas, Independent Movies, International Movies     252
Kids' TV                                             219
Children & Family Movies                             215
Children & Family Movies, Comedies                   201
Documentaries, International Movies                  186
Dramas, International Movies, Romantic Movies        180
Comedies, International Movies                       176
Comedies, International Movies, Romantic Movies      152
Dramas                                               137
Dramas, International Movies, Thrillers              134
Action & Adventure, Dramas, International Movies     132
Action & Adventure                                   128
International TV Shows, TV Dramas                    121
Comedies, Dramas, Independent Movies                 116
Comedies                                             110
Crime TV Shows, International TV Shows, TV Dramas    110
Name: show_id, dtype: int64

In [ ]:
df.groupby(["rating","type"]).size()

rating    type
G         Movie        41
NC-17     Movie         3
NR        Movie        75
          TV Show       4
PG        Movie       287
PG-13     Movie       490
R         Movie       797
          TV Show       2
TV-14     Movie      1427
          TV Show     730
TV-G      Movie       126
          TV Show      94
TV-MA     Movie      2062
          TV Show    1143
TV-PG     Movie       540
          TV Show     321
TV-Y      Movie       131
          TV Show     175
TV-Y7     Movie       139
          TV Show     194
TV-Y7-FV  Movie         5
          TV Show       1
UR        Movie         3
dtype: int64

In [ ]:
 df[df['type'] == 'Movie']

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in,month_added,year_added,day_added
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,2021-09-25,2020,PG-13,90 min,Documentaries,September,2021,Saturday
3,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,2021-09-22,2021,TV-PG,91 min,"Children & Family Movies, Comedies",September,2021,Wednesday
4,s8,Movie,Sankofa,Haile Gerima,United States,2021-09-24,1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies",September,2021,Friday
6,s10,Movie,The Starling,Theodore Melfi,United States,2021-09-24,2021,PG-13,104 min,"Comedies, Dramas",September,2021,Friday
7,s939,Movie,Motu Patlu in the Game of Zones,Suhas Kadav,India,2021-05-01,2019,TV-Y7,87 min,"Children & Family Movies, Comedies, Music & Mu...",May,2021,Saturday
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8702,s8232,Movie,The Bund,Not Given,Hong Kong,2018-09-20,1983,TV-14,103 min,"Action & Adventure, Dramas, International Movies",September,2018,Thursday
8707,s8269,Movie,The Darkest Dawn,Not Given,United Kingdom,2018-06-23,2016,TV-MA,75 min,"Action & Adventure, Independent Movies, Intern...",June,2018,Saturday
8716,s8331,Movie,The Great Battle,Not Given,South Korea,2019-04-08,2018,TV-MA,136 min,"Action & Adventure, Dramas, International Movies",April,2019,Monday
8763,s8648,Movie,"Twisted Trunk, Big Fat Body",Not Given,India,2017-01-15,2015,TV-14,89 min,"Dramas, International Movies",January,2017,Sunday
8783,s8785,Movie,Yoko and His Friends,Not Given,Russia,2018-06-23,2015,TV-Y,78 min,Children & Family Movies,June,2018,Saturday

In [ ]:
 df[df['type'] == 'TV Show']

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in,month_added,year_added,day_added
1,s3,TV Show,Ganglands,Julien Leclercq,France,2021-09-24,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",September,2021,Friday
2,s6,TV Show,Midnight Mass,Mike Flanagan,United States,2021-09-24,2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries",September,2021,Friday
5,s9,TV Show,The Great British Baking Show,Andy Devonshire,United Kingdom,2021-09-24,2021,TV-14,9 Seasons,"British TV Shows, Reality TV",September,2021,Friday
17,s4,TV Show,Jailbirds New Orleans,Not Given,Pakistan,2021-09-24,2021,TV-MA,1 Season,"Docuseries, Reality TV",September,2021,Friday
18,s15,TV Show,Crime Stories: India Detectives,Not Given,Pakistan,2021-09-22,2021,TV-MA,1 Season,"British TV Shows, Crime TV Shows, Docuseries",September,2021,Wednesday
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8785,s8797,TV Show,Yunus Emre,Not Given,Turkey,2017-01-17,2016,TV-PG,2 Seasons,"International TV Shows, TV Dramas",January,2017,Tuesday
8786,s8798,TV Show,Zak Storm,Not Given,United States,2018-09-13,2016,TV-Y7,3 Seasons,Kids' TV,September,2018,Thursday
8787,s8801,TV Show,Zindagi Gulzar Hai,Not Given,Pakistan,2016-12-15,2012,TV-PG,1 Season,"International TV Shows, Romantic TV Shows, TV ...",December,2016,Thursday
8788,s8784,TV Show,Yoko,Not Given,Pakistan,2018-06-23,2016,TV-Y,1 Season,Kids' TV,June,2018,Saturday
8789,s8786,TV Show,YOM,Not Given,Pakistan,2018-06-07,2016,TV-Y7,1 Season,Kids' TV,June,2018,Thursday

In [ ]:
df.groupby(['month_added', 'type']).size()

month_added  type
April        Movie      549
             TV Show    214
August       Movie      518
             TV Show    236
December     Movie      547
             TV Show    265
February     Movie      382
             TV Show    180
January      Movie      545
             TV Show    192
July         Movie      565
             TV Show    262
June         Movie      492
             TV Show    236
March        Movie      528
             TV Show    213
May          Movie      439
             TV Show    193
November     Movie      498
             TV Show    207
October      Movie      545
             TV Show    215
September    Movie      518
             TV Show    251
dtype: int64

In [ ]:
df.groupby(['year_added', 'type']).size()

year_added  type
2008        Movie         1
            TV Show       1
2009        Movie         2
2010        Movie         1
2011        Movie        13
2012        Movie         3
2013        Movie         6
            TV Show       5
2014        Movie        19
            TV Show       5
2015        Movie        56
            TV Show      26
2016        Movie       251
            TV Show     175
2017        Movie       836
            TV Show     349
2018        Movie      1237
            TV Show     411
2019        Movie      1424
            TV Show     592
2020        Movie      1284
            TV Show     595
2021        Movie       993
            TV Show     505
dtype: int64

In [ ]:
df.groupby(['day_added', 'type']).size()

day_added  type
Friday     Movie      1565
           TV Show     932
Monday     Movie       627
           TV Show     223
Saturday   Movie       557
           TV Show     259
Sunday     Movie       569
           TV Show     182
Thursday   Movie      1052
           TV Show     341
Tuesday    Movie       851
           TV Show     345
Wednesday  Movie       905
           TV Show     382
dtype: int64

In [ ]:
percentages = ((df['type'].value_counts() / len(df)) * 100).round(2)
percentages

type
Movie      69.69
TV Show    30.31
Name: count, dtype: float64

In [ ]:
df['release_year'].value_counts()

release_year
2018    1146
2019    1030
2017    1030
2020     953
2016     901
        ...
1961       1
1959       1
1925       1
1966       1
1947       1
Name: count, Length: 74, dtype: int64

In [ ]:
d = df[df['type'] == 'Movie']
d['rating'].value_counts()

rating
TV-MA       2062
TV-14       1427
R            797
TV-PG        540
PG-13        490
PG           287
TV-Y7        139
TV-Y         131
TV-G         126
NR            75
G             41
TV-Y7-FV       5
NC-17          3
UR             3
Name: count, dtype: int64